version: '3'
services:
  redis-server:
    image: 'redis'
  node-app:
    restart: always #if the container stops *for any reaason* always attemp to restart
    build: . #look in the current directory for a Dockerfile and use that to build this image
    ports:
      - "4041:8081"